spring.application.name=Projekt_ZTPAI
spring.datasource.url=jdbc:postgresql://localhost:5432/shelter
spring.datasource.username=nati
spring.datasource.password=natipass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
